Repository SKN-Telephoners/AGH-IX, pull requests merged in 2022-05, with the labels that each got.

#10 updating to use only local zerotier-api
  core/zerotier.py
Labels: dependencies

#11 Finish login
  Dockerfile
  agh_ix/settings.py
  agh_ix/urls.py
  core/admin.py
  core/forms.py
  core/migrations/0002_delete_profile.py
  core/models.py
  core/static/base.css
  core/static/logo.png
  core/templates/base.html
  core/templates/registration/login.html
  core/templates/registration/register.html
  core/views.py
  requirements.txt
Labels: enhancement

#12 Add network creation
  agh_ix/settings.py
  agh_ix/urls.py
  core/admin.py
  core/forms.py
  core/migrations/0001_initial.py
  core/migrations/0002_delete_profile.py
  core/migrations/__init__.py
  core/models.py
  core/static/base.css
  core/templates/base.html
  core/templates/core/add_connection.html
  core/templates/core/network.html
  core/templates/registration/login.html
  core/views.py
  core/zerotier.py
  docker-compose.yaml
  requirements.txt
Labels: enhancement

#13 zerotier default network
  core/zerotier.py
Labels: enhancement

#14 Auto connect zerotier network
  agh_ix/settings.py
  core/migrations/0001_initial.py
  core/migrations/__init__.py
  core/models.py
  core/views.py
  core/zerotier.py
  docker-compose.yaml
  requirements.txt
Labels: enhancement

#16 Add functioning connection status and better home page
  core/models.py
  core/templates/core/home.html
  core/views.py
  core/zerotier.py
Labels: documentation, enhancement

#17 Zerotier dockerised
  agh_ix/settings.py
  core/models.py
  core/templates/core/network.html
  core/views.py
  core/zerotier.py
  docker-compose.yaml
  docker/zerotier/Dockerfile
  zerotier.token
Labels: enhancement

#19 Add Assigned IP column in network overview
  core/forms.py
  core/migrations/0001_initial.py
  core/migrations/0002_baseconnection_assignedip.py
  core/migrations/0003_alter_baseconnection_assignedip.py
  core/migrations/__init__.py
  core/models.py
  core/templates/core/network.html
  core/views.py
  core/zerotier.py
Labels: enhancement

#27 Update README.md
  README.md
Labels: urgent
